/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "contract-reader",
  "name": "Legalese Lens",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Can I cancel anytime, and is there a fee?",
      "does": "Finds the right clauses and answers with citations."
    },
    {
      "say": "What changed in the new version?",
      "does": "Compares the two versions and summarizes the risk changes."
    },
    {
      "say": "Is this lease missing anything important?",
      "does": "Runs the lease checklist and lists the gaps."
    }
  ]
};
